// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using URFYSIO.Infrastructure.Data;

#nullable disable

namespace URFYSIO.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260731202329_AddCommentPhotoBlobName")]
    partial class AddCommentPhotoBlobName
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("URFYSIO.Core.Entities.Appointment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AvailabilitySlotId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ClientProfileId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<Guid>("PhysiotherapistProfileId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("AvailabilitySlotId")
                        .IsUnique()
                        .HasFilter("[AvailabilitySlotId] IS NOT NULL");

                    b.HasIndex("ClientProfileId");

                    b.HasIndex("PhysiotherapistProfileId");

                    b.ToTable("Appointments");
                });

            modelBuilder.Entity("URFYSIO.Core.Entities.AvailabilitySlot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsBooked")
                        .HasColumnType("bit");

                    b.Property<Guid>("PhysiotherapistProfileId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("PhysiotherapistProfileId");

                    b.ToTable("AvailabilitySlots");
                });

            modelBuilder.Entity("URFYSIO.Core.Entities.ClientProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("MedicalNotes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("ClientProfiles");
                });

            modelBuilder.Entity("URFYSIO.Core.Entities.PhysiotherapistProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LicenseNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Specialization")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("PhysiotherapistProfiles");
                });

            modelBuilder.Entity("URFYSIO.Core.Entities.RegistrationRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Message")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid?>("ProcessedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("ProcessedByUserId");

                    b.ToTable("RegistrationRequests");
                });

            modelBuilder.Entity("URFYSIO.Core.Entities.TreatmentPlan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ClientProfileId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("bit");

                    b.Property<Guid>("PhysiotherapistProfileId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ClientProfileId");

                    b.HasIndex("PhysiotherapistProfileId");

                    b.ToTable("TreatmentPlans");
                });

            modelBuilder.Entity("URFYSIO.Core.Entities.TreatmentPlanEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("bit");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("TreatmentPlanId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TreatmentPlanId");

                    b.ToTable("TreatmentPlanEntries");
                });

            modelBuilder.Entity("URFYSIO.Core.Entities.TreatmentPlanEntryComment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PhotoBlobName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<Guid>("TreatmentPlanEntryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TreatmentPlanEntryId");

                    b.HasIndex("UserId");

                    b.ToTable("TreatmentPlanEntryComments");
                });

            modelBuilder.Entity("URFYSIO.Core.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Auth0Id")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Gender")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("HouseNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("MustChangePassword")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("PostalCode")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Street")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("Auth0Id")
                        .IsUnique()
                        .HasFilter("Auth0Id IS NOT NULL");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("URFYSIO.Core.Entities.Appointment", b =>
                {
                    b.HasOne("URFYSIO.Core.Entities.AvailabilitySlot", "AvailabilitySlot")
                        .WithOne("Appointment")
                        .HasForeignKey("URFYSIO.Core.Entities.Appointment", "AvailabilitySlotId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("URFYSIO.Core.Entities.ClientProfile", "ClientProfile")
                        .WithMany("Appointments")
                        .HasForeignKey("ClientProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("URFYSIO.Core.Entities.PhysiotherapistProfile", "PhysiotherapistProfile")
                        .WithMany("Appointments")
                        .HasForeignKey("PhysiotherapistProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AvailabilitySlot");

                    b.Navigation("ClientProfile");

                    b.Navigation("PhysiotherapistProfile");
                });

            modelBuilder.Entity("URFYSIO.Core.Entities.AvailabilitySlot", b =>
                {
                    b.HasOne("URFYSIO.Core.Entities.PhysiotherapistProfile", "PhysiotherapistProfile")
                        .WithMany("AvailabilitySlots")
                        .HasForeignKey("PhysiotherapistProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PhysiotherapistProfile");
                });

            modelBuilder.Entity("URFYSIO.Core.Entities.ClientProfile", b =>
                {
                    b.HasOne("URFYSIO.Core.Entities.User", "User")
                        .WithOne("ClientProfile")
                        .HasForeignKey("URFYSIO.Core.Entities.ClientProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("URFYSIO.Core.Entities.PhysiotherapistProfile", b =>
                {
                    b.HasOne("URFYSIO.Core.Entities.User", "User")
                        .WithOne("PhysiotherapistProfile")
                        .HasForeignKey("URFYSIO.Core.Entities.PhysiotherapistProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("URFYSIO.Core.Entities.RegistrationRequest", b =>
                {
                    b.HasOne("URFYSIO.Core.Entities.User", "ProcessedByUser")
                        .WithMany()
                        .HasForeignKey("ProcessedByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ProcessedByUser");
                });

            modelBuilder.Entity("URFYSIO.Core.Entities.TreatmentPlan", b =>
                {
                    b.HasOne("URFYSIO.Core.Entities.ClientProfile", "ClientProfile")
                        .WithMany("TreatmentPlans")
                        .HasForeignKey("ClientProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("URFYSIO.Core.Entities.PhysiotherapistProfile", "PhysiotherapistProfile")
                        .WithMany("TreatmentPlans")
                        .HasForeignKey("PhysiotherapistProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ClientProfile");

                    b.Navigation("PhysiotherapistProfile");
                });

            modelBuilder.Entity("URFYSIO.Core.Entities.TreatmentPlanEntry", b =>
                {
                    b.HasOne("URFYSIO.Core.Entities.TreatmentPlan", "TreatmentPlan")
                        .WithMany("Entries")
                        .HasForeignKey("TreatmentPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TreatmentPlan");
                });

            modelBuilder.Entity("URFYSIO.Core.Entities.TreatmentPlanEntryComment", b =>
                {
                    b.HasOne("URFYSIO.Core.Entities.TreatmentPlanEntry", "TreatmentPlanEntry")
                        .WithMany("Comments")
                        .HasForeignKey("TreatmentPlanEntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("URFYSIO.Core.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TreatmentPlanEntry");

                    b.Navigation("User");
                });

            modelBuilder.Entity("URFYSIO.Core.Entities.AvailabilitySlot", b =>
                {
                    b.Navigation("Appointment");
                });

            modelBuilder.Entity("URFYSIO.Core.Entities.ClientProfile", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("TreatmentPlans");
                });

            modelBuilder.Entity("URFYSIO.Core.Entities.PhysiotherapistProfile", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("AvailabilitySlots");

                    b.Navigation("TreatmentPlans");
                });

            modelBuilder.Entity("URFYSIO.Core.Entities.TreatmentPlan", b =>
                {
                    b.Navigation("Entries");
                });

            modelBuilder.Entity("URFYSIO.Core.Entities.TreatmentPlanEntry", b =>
                {
                    b.Navigation("Comments");
                });

            modelBuilder.Entity("URFYSIO.Core.Entities.User", b =>
                {
                    b.Navigation("ClientProfile");

                    b.Navigation("PhysiotherapistProfile");
                });
#pragma warning restore 612, 618
        }
    }
}
